server:
  port: "8081"

square:
  env: "sandbox"
  applicationId: "sandbox-sq0idb-ubcXLoWLh9cqSzOWC9d8HQ"
  accessToken: "EAAAl34BbsaiuiPozN6WW7zgNSppZUf55ugLTHEHr4GfWPXjb6BOOIBicOmVLMCq"

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  name: "restaurant_db"